version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v12-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v12-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v12-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - save_cache:
          paths:
            - lib
          key: v12-build-{{ .Environment.CIRCLE_SHA1 }}
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: v12-dependencies-{{ checksum "package.json" }}
      - restore_cache:
          key: v12-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish --access public
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          context: NPM
          requires:
            - build
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
