on:
  pull_request:
    branches:
      - main
jobs:
  size:
    name: Size limit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: andresz1/size-limit-action@4135860a4890e227388c4735ece257be61a4c96d # tag=v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
