on:
  pull_request:
    branches:
      - main
jobs:
  size:
    name: Size limit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - uses: andresz1/size-limit-action@e7493a72a44b113341c0cf6186ab49c17c4b65c1 # tag=v1.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
