on:
  pull_request:
    branches:
      - main
jobs:
  size:
    name: Size limit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: andresz1/size-limit-action@4135860a4890e227388c4735ece257be61a4c96d # tag=v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
