on:
  pull_request:
    branches:
      - main
jobs:
  size:
    name: Size limit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: andresz1/size-limit-action@v1.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
