on:
  pull_request:
    branches:
      - main
jobs:
  size:
    name: Size limit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: andresz1/size-limit-action@4135860a4890e227388c4735ece257be61a4c96d # tag=v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
